Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 532, in parse_int
    return int(v, 0)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 0: '0x130000  # Aumentamos a 1.2 MB'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 184, in from_csv
    res.append(PartitionDefinition.from_csv(line, line_no + 1))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 373, in from_csv
    res.size = res.parse_address(fields[4])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 430, in parse_address
    return parse_int(strval)
           ^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 535, in parse_int
    raise InputError('Invalid field value %s' % v)
gen_esp32part.InputError: Invalid field value 0x130000  # Aumentamos a 1.2 MB

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 363, in <module>
    main()
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 332, in main
    target = ParttoolTarget(**target_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/parttool.py", line 97, in __init__
    partition_table = gen.PartitionTable.from_csv(f.read())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ivanool/esp/esp-idf/components/partition_table/gen_esp32part.py", line 186, in from_csv
    raise InputError('Error at line %d: %s\nPlease check extra_partition_subtypes.inc file in build/config directory' % (line_no + 1, err))
gen_esp32part.InputError: Error at line 6: Invalid field value 0x130000  # Aumentamos a 1.2 MB
Please check extra_partition_subtypes.inc file in build/config directory
